# Supplement

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(tidyverse)
library(dplyr)
library(broom)
library(reshape2)
library(glmnet)
library(readr)

## Graphics
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(ppcor)
library(ggExtra)
library(ggsci)
library(viridis)
library(scales)
library(patchwork)# Multi-plot alignment
library(ggcorrplot)
library(gapminder) # dataset used to make the box plot connected by lines
library(RColorBrewer) 
library(plotly) # Added to make interactive graphs 
library(lubridate) # Added to make interactive graphs; use different date funcs
library(stringr) # Added to make interactive graphs; use different txt funcs
library(extrafont) # Added to make interactive graphs; change font on graphs
library(htmlwidgets) # Added to make interactive graphs; make exports interactive
library(cowplot)

## Tables
library(kableExtra)
library(xtable)

# Date functions
library(anytime)
library(lubridate)

# SlimStampen

#install.packages("devtools") # Install SlimStampen packages. Instructions on https://github.com/VanRijnLab/SlimStampeRData
library(devtools)
#devtools::install_github("VanRijnLab/SlimStampeRData",
                      #   build_vignettes = TRUE,
                       #  dependencies = TRUE,
                        # force = TRUE) 
# The console will show a prompt asking whether all packages should be updated. Select option 1 (by typing 1 and then pressing enter), this will update all packages.
vignette("SlimStampeRVignette")
library(SlimStampeRData)

```


```{r, echo=FALSE, results= 'hide'}

# Load data
load("C:/Users/17203/Documents/GitHub/Blaarkop/data/SlimStampen_2022-08-18.RData")

# Filter for just ADRC subjects & group by clinical status
groups <- read_csv("C:/Users/17203/Documents/GitHub/Blaarkop/groups.csv", show_col_types = FALSE)
data %>% 
  filter(userId %in% groups$userId) -> data

```

```{r, echo=FALSE, results= 'hide'}

# Calculate fact rep, activation, and alpha 
MAX_ALPHA=0.8
data <- data %>%
  calculate_repetition() %>%
  calculate_alpha_and_activation(maxAlpha=MAX_ALPHA)

```
```{r, echo=FALSE, results= 'hide'}


# Group by Clinical Status
data <- inner_join(data, groups)

```

```{r}

# Filter the sessions
sessionData <- data %>% 
  group_by(userId, sessionId, lessonId, lessonTitle) %>% 
  summarize(duration = (max(presentationStartTime) - min(presentationStartTime))/60000,
            start = min(presentationStartTime),
            legit = if_else(duration > 6, T, F)) 

sessionData <- sessionData %>% 
  group_by(userId, lessonId, lessonTitle) %>% 
  arrange(start, by_group=T) %>%
  mutate(sessionRank = seq(1, length(start)))

sessionDataFiltered <- sessionData %>%
  filter(legit == T) %>%
  group_by(userId, lessonId) %>%
  mutate(minRank = min(sessionRank))

sessionData <- sessionData %>%
  inner_join(sessionDataFiltered) %>%
  mutate(usable = if_else(minRank == sessionRank, T, F))


cleandata <- inner_join(sessionData, data) %>%
  filter(usable == T)

cleandata$userId <- as.character(cleandata$userId)

# Change reactionTime from ms to s
cleandata$reactionTime <- (cleandata$reactionTime/1000)


```

```{r}

# Filter by task 
Pasta=filter(cleandata,lessonTitle=='Pasta')
Swahili1=filter(cleandata,lessonTitle=='Swahili 1')
Flowers=filter(cleandata,lessonTitle=='Flowers')  
Capitals=filter(cleandata,lessonTitle=='European Capitals 1') 
Birds=filter(cleandata,lessonTitle=='Birds') 
News=filter(cleandata,lessonTitle=='Newspapers') 
Flags=filter(cleandata,lessonTitle=='Asian Flags') 
Folktales=filter(cleandata,lessonTitle=='Folktales') 
Maps=filter(cleandata,lessonTitle=='Maps') 
USTowns=filter(cleandata,lessonTitle=='US Towns 1') 

```

## Lesson Fact Reaction Times

```{r, echo=FALSE}

ggplot(data, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time") +
  ggtitle("Reaction Time for Each Fact (unfiltered)") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))

# filtered for complete session data
ggplot(cleandata, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time") +
  ggtitle("Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))

ggplot(Pasta, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Pasta: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(Swahili1, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Swahili: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(Flowers, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Flowers: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(Capitals, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Capitals: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(Birds, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Birds: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(News, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("News: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(Flags, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Flags: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(Folktales, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Folktales: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


ggplot(Maps, aes(x=factAnswer, y=reactionTime))+
  geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Maps: Reaction Time for Each Fact") +
  theme_pander() +
  theme(legend.position = "none",
        axis.text.x = element_text (angle=90))


#ggplot(USTowns1, aes(x=factAnswer, y=reactionTime))+
 # geom_point(size=1, position=position_jitter(0.1), aes(color= "purple3")) +
  #     xlab("Fact") +
 # ylab("Reaction Time (ms)") +
 # ggtitle("US Towns 1: Reaction Time for Each Fact") +
 # theme_pander() +
 # theme(legend.position = "none",
     #   axis.text.x = element_text (angle=90))

```

### Reaction Time for each fact (interactive)

```{r, echo=FALSE}

graph=ggplot(Pasta, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Pasta: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90))
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(Swahili1, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Swahili: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90))
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(Flowers, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Flowers: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90))
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(Capitals, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Capitals: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90))
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(Birds, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Birds: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90))
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(News, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("News: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90))
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(Flags, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Flags: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90))
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(Folktales, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Folktales: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90),
        panel.grid.major = element_blank())
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


graph=ggplot(Maps, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
  geom_point(size=1, position=position_jitter(0.1)) +
       xlab("Fact") +
  ylab("Reaction Time (ms)") +
  ggtitle("Maps: Reaction Time for Each Fact") +
  labs(col="Participant") +
  theme_pander() +
  theme(legend.position = "right",
        axis.text.x = element_text (angle=90),
        panel.grid.major = element_blank())
ggplotly(graph, tooltip=c("y", "text")) %>% 
  config(displayModeBar=FALSE)


#graph=ggplot(USTowns1, aes(x=factAnswer, y=reactionTime, col=userId, text=paste0(userId)))+
 # geom_point(size=1, position=position_jitter(0.1)) +
  #     xlab("Fact") +
  #ylab("Reaction Time (ms)") +
  #ggtitle("US Towns 1: Reaction Time for Each Fact") +
  #labs(col="Participant") +
  #theme_pander() +
  #theme(legend.position = "right",
   #     axis.text.x = element_text (angle=90),
    #    panel.grid.major = element_blank())
#ggplotly(graph, tooltip=c("y", "text")) %>% 
 # config(displayModeBar=FALSE)




```


```{r, echo=FALSE, results= 'hide'}

# Filter by task  
Pasta=filter(data,lessonTitle=='Pasta')
Swahili1=filter(data,lessonTitle=='Swahili 1')
Flowers=filter(data,lessonTitle=='Flowers')  
Capitals=filter(data,lessonTitle=='European Capitals 1') 
Birds=filter(data,lessonTitle=='Birds') 
News=filter(data,lessonTitle=='Newspapers') 
Flags=filter(data,lessonTitle=='Asian Flags') 
Folktales=filter(data,lessonTitle=='Folktales') 

```


```{r, echo=FALSE, results= 'hide'}

# Function
## Average Rate of Forgetting for Every Fact 

average_ROF_facts <- function(data, factNames = "factId", xlim = NULL, ylim = NULL) {
  if(missing(data)){
    stop("No data is provided")
  }
  if(!("repetition" %in% colnames(data))){
    stop("No repetition column is provided in the data, run calculate_repetition() to add a repetition column to the data")
  }
  if(!("alpha" %in% colnames(data))){
    stop("No alpha column is provided in the data, run calculate_alpha_and_activation() to add an alpha column to the data")
  }

  if(!(is.null(xlim) | length(xlim) == 2)){
    stop("xlim must be a vector of 2")
  }
  if(!(is.null(ylim) | length(ylim) == 2)){
    stop("ylim must be a vector of 2")
  }
  
  # Prints a message when the column contains missing values
missing_values_message <- function(data, columns) {
  indx <- apply(data, 2, function(x) any(is.na(x)))
  for(col in columns){
    if(col %in% colnames(data)[indx]){
      cat("! There are missing values in the column ", col, " ! \n")
    }
  }
}

# Returns a non-empty vector when a column is missing
  
  missing_columns_check <- function(data, columns) {
  missingcols <- character(0)
  for(col in columns){
    if(!(col %in% colnames(data))){
      missingcols[[1]] <- col
    }
  }
  return(missingcols)
}
  
  missingcol <- missing_columns_check(data, c("sessionId", "alpha", "repetition", "factId", "lessonId", "userId", "presentationStartTime", factNames))
  if(length(missingcol) > 0){
    stop("No ", missingcol[[1]] ," column is provided in the data")
  }

  if(-1 %in% data$factId){
    data <- resetremoval(data)
    cat("- There are resets present in the data. Reset data is excluded in this function. - \n")
  }

  missing_values_message(data, c("sessionId", "alpha", "repetition", "factId", factNames))

  #Only the first session of a user within a lesson is kept in the data
firstsession <- function(df) {
  dfgroup <- dplyr::group_by(df, lessonId, userId)
  dfsort <- dplyr::arrange(dfgroup, presentationStartTime, .by_group = TRUE)
  dfclean <- dplyr::filter(dfsort, sessionId == unique(sessionId)[1])
  dffree <- dplyr::ungroup(dfclean)
  return(dffree)
}
  
  data <- firstsession(data)

  cat("This may take a moment... \n")
  plotTitle <- paste("Rate of Forgetting for Each Fact")
  plot <- NULL

  facts <- sort(unique(data$factId))
  factcolor <- viridis::turbo(length(facts))
  names(factcolor)  <- facts

  # Group by sessionId and repetition, then mean alpha as new column
  dat1 <- dplyr::group_by(.data = data, factId, repetition)
  dat2 <- dplyr::summarise(.data = dat1, mean_alpha = mean(alpha, na.rm=TRUE), factLabels = unique(.data[[factNames]])[[1]])
  dat2$factLabels = substr(dat2$factLabels, 1, 10)
  dat3 <- dplyr::group_by(.data = dat2, factId)
  dat4 <- dplyr::filter(.data = dat3, repetition == max(repetition))
  dat5 <- dat4[order(dat4$mean_alpha, decreasing = TRUE),]

 # y = ylim
  #x = xlim

  # Make plot HH
  #plot <- ggplot2::ggplot(data = dat2, ggplot2::aes(x = factor(repetition), y = mean_alpha, group = factId)) +
   # ggplot2::geom_line(alpha = 1, ggplot2::aes(colour = factor(factId))) +
  #  ggplot2::geom_point(alpha = 0.5, size = 1, ggplot2::aes(colour = factor(factId), fill = factor(factId))) +
   # ggplot2::geom_point(data = dat5, alpha = 0.5, size = 3, position = ggplot2::position_jitter(w = 0.08, h = 0), ggplot2::aes(colour = factor(factId), fill = factor(factId))) +
  #  ggplot2::scale_color_manual(name="Facts", labels = dat5$factLabels,values = factcolor, breaks=dat5$factId) +
   # ggplot2::guides(fill = "none") +
    #ggplot2::coord_cartesian(xlim = x, ylim = y) +
  #  ggplot2::labs(x = "Fact Repetitions", y = "Alpha") +
   # theme_pander() +
    #ggplot2::theme(legend.position="right") +
    #ggplot2::guides(colour=ggplot2::guide_legend(nrow=18, byrow=FALSE)) +
    #ggplot2::ggtitle(plotTitle)
  
  #plot
  
}
```


```{r}
Pasta_AVG_RoF_Facts <- Pasta %>%
  average_ROF_facts()

Pasta_AVG_RoF_Facts <- inner_join(Pasta, Pasta_AVG_RoF_Facts)

```

```{r}


  #  Make plot HH
 # plot <- ggplot(Pasta_AVG_RoF_Facts, aes(x = factor(repetition), y = mean_alpha, group = factId)) +
   # geom_line(alpha = 1, aes(colour = factor(factId))) +
  #  geom_point(alpha = 0.5, size = 1, aes(colour = factor(factId), fill = factor(factId))) +
  #  geom_point(Pasta_AVG_RoF_Facts, alpha = 0.5, size = 3, position = position_jitter(w = 0.08, h = 0), aes(colour = factor(factId), fill = factor(factId))) +
  #  scale_color_manual(name="Facts", labels = factLabels,values = factcolor, breaks=factId) +
  #  guides(fill = "none") +
  #  coord_cartesian(xlim = x, ylim = y) +
  #  labs(x = "Fact Repetitions", y = "Alpha") +
  #  theme_pander() +
 #   theme(legend.position="right") +
  #  guides(colour=guide_legend(nrow=18, byrow=FALSE)) +
  #  ggtitle(plotTitle)
  
 # plot
```



```{r, echo=FALSE, results= 'hide'}

# Function
## Average Rate of Forgetting for Every Participant in Each Lesson

average_ROF_participants <- function(data, xlim = NULL, ylim = NULL, userId = "userId") {
  if(missing(data)){
    stop("No data is provided")
  }
  if(!("repetition" %in% colnames(data))){
    stop("No repetition column is provided in the data, run calculate_repetition() to add a repetition column to the data")
  }
  if(!("alpha" %in% colnames(data))){
    stop("No alpha column is provided in the data, run calculate_alpha_and_activation() to add an alpha column to the data")
  }
  
    # Prints a message when the column contains missing values
missing_values_message <- function(data, columns) {
  indx <- apply(data, 2, function(x) any(is.na(x)))
  for(col in columns){
    if(col %in% colnames(data)[indx]){
      cat("! There are missing values in the column ", col, " ! \n")
    }
  }
}

# Returns a non-empty vector when a column is missing
  
  missing_columns_check <- function(data, columns) {
  missingcols <- character(0)
  for(col in columns){
    if(!(col %in% colnames(data))){
      missingcols[[1]] <- col
    }
  }
  return(missingcols)
}
  
  missingcol <- missing_columns_check(data, c("sessionId", "alpha", "repetition", "lessonId", "userId", "presentationStartTime", "factId"))
  if(length(missingcol) > 0){
    stop("No ", missingcol[[1]] ," column is provided in the data")
  }

  if(!(is.null(xlim) | length(xlim) == 2)){
    stop("xlim must be a vector of 2")
  }
  if(!(is.null(ylim) | length(ylim) == 2)){
    stop("ylim must be a vector of 2")
  }

  if(-1 %in% data$factId){
    data <- resetremoval(data)
    cat("- There are resets present in the data. Reset data is excluded in this function. - \n")
  }

  missing_values_message(data, c("sessionId", "alpha", "repetition"))
  
    #Only the first session of a user within a lesson is kept in the data
firstsession <- function(df) {
  dfgroup <- dplyr::group_by(df, lessonId, userId)
  dfsort <- dplyr::arrange(dfgroup, presentationStartTime, .by_group = TRUE)
  dfclean <- dplyr::filter(dfsort, sessionId == unique(sessionId)[1])
  dffree <- dplyr::ungroup(dfclean)
  return(dffree)
}

  data <- firstsession(data)

  participants <- sort(unique(data$userId))
  partcolor <- viridis::turbo(length(participants))
  names(partcolor)  <- participants

  cat("This may take a moment... \n")
  plotTitle <- paste("RoF for Each Participant")
  plot <- NULL

  # Group by sessionId and repetition, then mean alpha as new column
  dat1 <- dplyr::group_by(.data = data, userId, repetition)
  dat2 <- dplyr::summarise(.data = dat1, mean_alpha = mean(alpha, na.rm=TRUE),Participant = unique(.data[[userId]])[[1]])
  dat2$Participant = substr(dat2$Participant, 1, 10)
  dat3 <- dplyr::group_by(.data = dat2, userId)
  dat4 <- dplyr::filter(.data = dat3, repetition == max(repetition))
  dat5 <- dat4[order(dat4$mean_alpha, decreasing = TRUE),]

  y = ylim
  x = xlim

  # Make plot
  plot <- ggplot2::ggplot(data = dat2, ggplot2::aes(x = factor(repetition), y = mean_alpha, group = userId)) +
    ggplot2::geom_line(alpha = 1, ggplot2::aes(colour = factor(userId))) +
    ggplot2::geom_point(alpha = 0.5, size = 1, ggplot2::aes(colour = factor(userId), fill = factor(userId))) +
    ggplot2::geom_point(data = dat5, alpha = 0.5, size = 3, position = ggplot2::position_jitter(w = 0.08, h = 0), ggplot2::aes(colour = factor(userId), fill = factor(userId))) +
    ggplot2::scale_color_manual(name="Participants", labels = dat5$Participant,values = partcolor, breaks=dat5$userId) +
    ggplot2::guides(fill = "none") +
    ggplot2::coord_cartesian(xlim = x, ylim = y) +
    ggplot2::labs(x = "Fact Repetitions", y = "Alpha") +
    theme_pander() +
    ggplot2::theme(legend.position="right") +
    ggplot2::guides(colour=ggplot2::guide_legend(nrow=18, byrow=FALSE)) +
    ggplot2::ggtitle(plotTitle)
    
  plot

    
}   

```

```{r, echo=FALSE, results= 'hide'}

# Function
## Average Rate of Forgetting for Every Participant in Each Lesson (Interactive)
### Interactive

average_ROF_participants_interactive <- function(data, xlim = NULL, ylim = NULL, userId = "userId") {
  if(missing(data)){
    stop("No data is provided")
  }
  if(!("repetition" %in% colnames(data))){
    stop("No repetition column is provided in the data, run calculate_repetition() to add a repetition column to the data")
  }
  if(!("alpha" %in% colnames(data))){
    stop("No alpha column is provided in the data, run calculate_alpha_and_activation() to add an alpha column to the data")
  }
  
    # Prints a message when the column contains missing values
missing_values_message <- function(data, columns) {
  indx <- apply(data, 2, function(x) any(is.na(x)))
  for(col in columns){
    if(col %in% colnames(data)[indx]){
      cat("! There are missing values in the column ", col, " ! \n")
    }
  }
}

# Returns a non-empty vector when a column is missing
  
  missing_columns_check <- function(data, columns) {
  missingcols <- character(0)
  for(col in columns){
    if(!(col %in% colnames(data))){
      missingcols[[1]] <- col
    }
  }
  return(missingcols)
}
  
  missingcol <- missing_columns_check(data, c("sessionId", "alpha", "repetition", "lessonId", "userId", "presentationStartTime", "factId"))
  if(length(missingcol) > 0){
    stop("No ", missingcol[[1]] ," column is provided in the data")
  }

  if(!(is.null(xlim) | length(xlim) == 2)){
    stop("xlim must be a vector of 2")
  }
  if(!(is.null(ylim) | length(ylim) == 2)){
    stop("ylim must be a vector of 2")
  }

  if(-1 %in% data$factId){
    data <- resetremoval(data)
    cat("- There are resets present in the data. Reset data is excluded in this function. - \n")
  }

  missing_values_message(data, c("sessionId", "alpha", "repetition"))
  
    #Only the first session of a user within a lesson is kept in the data
firstsession <- function(df) {
  dfgroup <- dplyr::group_by(df, lessonId, userId)
  dfsort <- dplyr::arrange(dfgroup, presentationStartTime, .by_group = TRUE)
  dfclean <- dplyr::filter(dfsort, sessionId == unique(sessionId)[1])
  dffree <- dplyr::ungroup(dfclean)
  return(dffree)
}

  data <- firstsession(data)

  participants <- sort(unique(data$userId))
  partcolor <- viridis::turbo(length(participants))
  names(partcolor)  <- participants

  cat("This may take a moment... \n")
  plotTitle <- paste("RoF for Each Participant")
  plot <- NULL

  # Group by sessionId and repetition, then mean alpha as new column
  dat1 <- dplyr::group_by(.data = data, userId, clinicalStatus, repetition)
  dat2 <- dplyr::summarise(.data = dat1, mean_alpha = mean(alpha, na.rm=TRUE),Participant = unique(.data[[userId]])[[1]])
  dat2$Participant = substr(dat2$Participant, 1, 10)
  dat3 <- dplyr::group_by(.data = dat2, userId)
  dat4 <- dplyr::filter(.data = dat3, repetition == max(repetition))
  dat5 <- dat4[order(dat4$mean_alpha, decreasing = TRUE),]

  y = ylim
  x = xlim

  # Make plot
  graph.interactiveplot=ggplot2::ggplot(data = dat2, ggplot2::aes(x = factor(repetition), y = mean_alpha, group = userId, col=clinicalStatus, fill=clinicalStatus, text=paste0(userId))) +
    ggplot2::geom_line(alpha = 1, ggplot2::aes(colour = factor(clinicalStatus))) +
    ggplot2::geom_point(alpha = 0.5, size = 1, ggplot2::aes(colour = factor(clinicalStatus), fill = factor(clinicalStatus))) +
    ggplot2::geom_point(data = dat5, alpha = 0.5, size = 3, position = ggplot2::position_jitter(w = 0.08, h = 0), ggplot2::aes(colour = factor(clinicalStatus), fill = factor(clinicalStatus))) +
    scale_color_manual(values = c("gold3", "purple3")) +
  scale_fill_manual(values = c("gold3", "purple3")) +
    #ggplot2::scale_color_manual(name="Participants", labels = dat5$Participant,values = partcolor, breaks=dat5$userId) +
    ggplot2::guides(fill = "none") +
    ggplot2::coord_cartesian(xlim = x, ylim = y) +
    ggplot2::labs(x = "Fact Repetitions", y = "Alpha") +
    labs(col="Clinical Status", fill="Clinical Status") +
    theme_pander() +
    ggplot2::theme(legend.position="right") +
    ggplot2::guides(colour=ggplot2::guide_legend(nrow=18, byrow=FALSE)) +
    ggplot2::ggtitle(plotTitle)
    
  ggplotly(graph.interactiveplot, tooltip=c("y", "text")) %>% 
  layout(legend = list(orientation = "h")) %>% 
  config(displayModeBar=FALSE)
    
}    
```

## Lesson Facts RoF

### Average Rate of Forgetting for Each Lesson's Facts

```{r}
average_ROF_facts(Pasta, factNames = "factAnswer")
average_ROF_facts(Swahili1, factNames = "factAnswer")
average_ROF_facts(Flowers, factNames = "factAnswer")
average_ROF_facts(Capitals, factNames = "factAnswer")
average_ROF_facts(Birds, factNames = "factAnswer")
average_ROF_facts(News, factNames = "factAnswer")
average_ROF_facts(Flags, factNames = "factAnswer")

```
```{r}
average_ROF_facts(Pasta, factNames = "factAnswer")
average_ROF_facts(Swahili1, factNames = "factAnswer")
average_ROF_facts(Flowers, factNames = "factAnswer")
average_ROF_facts(Capitals, factNames = "factAnswer")
average_ROF_facts(Birds, factNames = "factAnswer")
average_ROF_facts(News, factNames = "factAnswer")
average_ROF_facts(Flags, factNames = "factAnswer")

```


## Lesson Participant RoF

### Average Rate of Forgetting for Every Participant in Each Lesson

```{r}
average_ROF_participants(Pasta, userId = "userId")
average_ROF_participants(Swahili1, userId = "userId")
average_ROF_participants(Flowers, userId = "userId")
average_ROF_participants(Capitals, userId = "userId")
average_ROF_participants(Birds, userId = "userId")
average_ROF_participants(News, userId = "userId")
average_ROF_participants(Flags, userId = "userId")

```

### Average Rate of Forgetting for Every Participant in Each Lesson (Interactive)

#### By Clinical Status

```{r}
average_ROF_participants_interactive(Pasta, userId = "userId")
average_ROF_participants_interactive(Swahili1, userId = "userId")
average_ROF_participants_interactive(Flowers, userId = "userId")
average_ROF_participants_interactive(Capitals, userId = "userId")
average_ROF_participants_interactive(Birds, userId = "userId")
average_ROF_participants_interactive(News, userId = "userId")
average_ROF_participants_interactive(Flags, userId = "userId")

```